### ISSUE TITLE
docker event logging is very misleading

### ISSUE THREAD

**Issue by soulware** [convox/agent#19]
The log msgs that are generated on `kill`, `die` and `stop` are very misleading - 

```
2016-03-10 04:21:48 i-8ecb8f49 convox/agent:0.66 : Stopped web process 88d1fb3c818d via SIGKILL
2016-03-10 04:21:48 i-8ecb8f49 convox/agent:0.66 : Dead web process 88d1fb3c818d
2016-03-10 04:21:48 i-8ecb8f49 convox/agent:0.66 : Stopped web process 88d1fb3c818d via SIGTERM
```

A `kill` event may not actually involve `SIGKILL` (you can pass an arbitrary signal into `docker kill`).
A `die` event may not actually indicate a process is dead at that point in time - just that it is "dying".
A `stop` event may involve more than just a `SIGTERM` (a `SIGKILL` 30s later may be involved).

I think it would be _far_ more intuitive if the log msgs here simply indicated the events that docker handled and not what we think has just happened.

Specifically - these 3 log msgs are generated when you call `convox ps stop` on a docker container that safely handles a `SIGTERM` and shuts down cleanly. `SIGKILL` was never actually involved here.

**Comment by ddollar** [comment]
This verbiage has been changed since this was filed. Please reopen if this is still an issue.
